services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

  seed:
    build: ./company/backend
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/jobs
    command: ["npm", "run", "seed"]
    
  backend:
    build: ./company/backend
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - mongo-express
      - seed
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/jobs

